package com.insert.recruitment.error;

public enum ReasonCode {
  ORDER_NOT_EXIST,
  CANNOT_CHANGE_ORDER_STATUS,
  REQUEST_VALIDATION,
  SQL_INTEGRITY_CONSTRAINT_VALIDATION,
  METHOD_NOT_ALLOW,
  ARGUMENT_TYPE_MISMATCH,
  MISSING_PATH_VARIABLE,
  MESSAGE_NOT_READABLE,
  METHOD_ARGUMENT_NOT_VALID
}
